### ISSUE TITLE
Support for arbitrary input streams

### ISSUE THREAD

**Issue by sevko** [mbostock/shapefile#15]
Would it be possible to have `shapefile.reader()` support an arbitrary data stream as an argument, instead of only a filename?

**Comment by calvinmetcalf** [comment]
see #18

**Comment by sevko** [comment]
Awesome.

**Comment by mbostock** [comment]
Sorry it took me so long to reply. I’ve just merged a rewrite of this library with an easier-to-use promise-y API based on [file-source](https://github.com/mbostock/file-source). Unfortunately, for now it’s still limited to files, but I’m planning on implementing [stream-source](https://github.com/mbostock/stream-source) that would provide an equivalent API for reading from Node streams, and then it should be trivial to add support here.

Related to this, it’d also be nice to support parsing of in-memory blobs, and perhaps [streaming response bodies](https://jakearchibald.com/2016/streams-ftw/) in the browser Fetch API.

**Comment by mbostock** [comment]
Okay, here’s what I think we should support. 

In Node:

- [ ] shapefile.read(*shp*[, *dbf*])

  If typeof *shp* is “string”, reads the .shp file at the specified *shp* path and the .dbf file at the specified *dbf* path. If *dbf* is not specified, it defaults to *shp* with the “.shp” extension replaced with “.dbf”; in this case, no error is thrown if there is no .dbf file at the resulting implied *dbf*. If *dbf* is explicitly specified, an error is thrown if the file does not exist.

  If *shp* instanceof ArrayBuffer or *shp* instanceof Uint8Array, reads the specified in-memory .shp file, and if specified, the .dbf file.

  Otherwise, reads the .shp file from the specified *shp* stream, and if specified, the .dbf file from the specified *dbf* stream. Both *shp* and *dbf*, if present, must be Node [readable streams](https://nodejs.org/api/stream.html#stream_readable_streams).

- [ ] shapefile.source(*shp*[, *dbf*])

  Like shapefile.read, but for streaming records.

In Browser:

- [ ] shapefile.read(*shp*[, *dbf*])

  If typeof *shp* is “string”, fetches the .shp file at the specified *shp* URL and the .dbf file at the specified *dbf* URL. If *dbf* is not specified, it defaults to *shp* with the “.shp” extension replaced with “.dbf”; in this case, no error is thrown if an error occurs loading the .dbf file at the resulting implied *dbfUrl*. If *dbf* is explicitly specified, an error is thrown if the file does not exist.

  If *shp* instanceof ArrayBuffer or *shp* instanceof Uint8Array, reads the specified in-memory .shp file, and if specified, the .dbf file.

  Otherwise, reads the .shp file from the specified *shp* stream, and if specified, the .dbf file from the specified *dbf* stream. Both *shp* and *dbf*, if present, must be WhatWG [readable streams](https://streams.spec.whatwg.org/#rs), such as a fetch [*response*.body](https://fetch.spec.whatwg.org/#concept-body), with a *stream*.getReader method.

Internal API:

- [ ] source(*shp*[, *dbf*])

  Like shapefile.read, but for streaming records.

**Comment by mbostock** [comment]
Interested parties can review and discuss over in #23.

**Comment by mbostock** [comment]
Now available in 0.5!
