### ISSUE TITLE
how to iterate over a record object

### ISSUE THREAD

**Issue by CruncherBigData** [mbostock/shapefile#17]
Hi, 
I posted this questions http://stackoverflow.com/questions/29548558/how-to-iterate-over-a-shapefile-in-node-js

the code is based on https://github.com/mbostock/shapefile/blob/master/test/shp-test.js

I am unable to iterate over the code! any idea why ?

**Comment by mbostock** [comment]
I’ve redesigned this library to use promises to make it (hopefully) easier to stream shapefiles. As before, there are two ways to do it. The easiest is to just load the whole file in memory using [shapefile.read](https://github.com/mbostock/shapefile#read):

```js
shapefile.read("example.shp")
  .then((collection) => console.log(collection))
  .catch((error) => console.error(error.stack));
```

If you prefer, you can use [*source*.record](https://github.com/mbostock/shapefile#source_record) to instead iterate over each record as a streaming API. This is more efficient because it avoids loading the whole shapefile into memory. For example:

```js
shapefile.open("example.shp")
  .then((source) => source.header()
    .then((header) => console.log(header))
    .then(function repeat() { return source.record()
      .then((record) => record && (console.log(record), repeat())); })
    .catch((error) => source.close().then(() => { throw error; }))
    .then(() => source.close()))
  .catch((error) => console.error(error.stack));
```
