### ISSUE TITLE
Tests are broken since 0.5.

### ISSUE THREAD

**Issue by jgravois** [mbostock/shapefile#25]
ran into the error below when running `npm test`

```bash
> shapefile@0.5.3 test /Users/john6251/github/shapefile
> tape 'test/**/*-test.js'

/Users/john6251/github/shapefile/dbf/index.js:1
(function (exports, require, module, __filename, __dirname) { import slice from "slice-source";
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
```
tape doesn't appear to be happy being pointed straight at the ES6 source (at least on my box), but since i don't have any trouble running `d3` tests locally that follow the same pattern, i'm stumped as to what i could have misconfigured.

**Comment by mbostock** [comment]
Yeah, sorry, I haven’t updated the internal dbf-test.js and shp-test.js since 0.5. Those tests need to be rewritten to use the public API; they currently use the private internal API which is no longer available on Node (since they are written in ES6 and transpiled to ES5 using Rollup, and the resulting bundle doesn’t expose the internal methods).

I did just fix a small error in index-test.js and so that works now, though.

**Comment by jgravois** [comment]
no worries. thanks for clarifying!
