### ISSUE TITLE
When string values are decoded, null values are added to the end of the string.

### ISSUE THREAD

**Issue by DaveOke** [mbostock/shapefile#29]
It looks like trimming white spaces at the end was intentional - suggest the following code to trim the null values as well.

```js
export default function(value) {
  return value.replace(/\0/g, '').trim() || null;
}
```

**Comment by mbostock** [comment]
I intend to investigate.

**Comment by mbostock** [comment]
I don’t have any examples of dBASE files that have leading or trailing null characters in them, so I can’t reproduce this problem. According to the [dBASE documentation](http://www.dbase.com/KnowledgeBase/int/db7_file_fmt.htm), it’s expected that character and numeric fields are “padded with blanks to the width of the field”, and the interpretation of a blank character is 0x20 (SPACE), not 0x0 (NULL). If there is a case where you have a NULL-terminated string (rather than a SPACE-padded one), you probably want to find the index of the first NULL character and then slice the string at that point, rather than just dropping the NULL characters wherever they occur. But as I don’t have any .dbf files formatted this way, it’s just speculation. If you can provide me with some test files to reproduce this behavior, I would be happy to reopen this issue and investigate.
