### ISSUE TITLE
Holes stick to outside area are not read accordingly

### ISSUE THREAD

**Issue by mickeyjohn** [mbostock/shapefile#59]
Hi, 
Thanks for making a good library. I found it does not read holes that stick to outside of its outer rings properly even though the coordinates are in CCW order. Instead, It will read the holes as normal overlapped polygons. Please refer to the screenshot.
![Screenshot from 2019-03-27 14-39-42](https://user-images.githubusercontent.com/14140486/55103129-45589980-509e-11e9-9d59-ae5bc29f9d9f.png)

Shouldn't we need to check the holes must be fully within theirs outer rings? 
Thank you.

**Comment by rdmurphy** [comment]
Flagging that I'm also seeing this too. 👋

**Comment by mbostock** [comment]
The shapefile format has different semantics than GeoJSON; it relies on winding order to indicate holes. GeoJSON in contrast represents polygons with holes as a series of rings: an outer clockwise ring and zero or more counterclockwise holes. So GeoJSON uses grouping in addition to winding order.

It’s not valid GeoJSON for a hole to go outside its containing ring. This library therefore tests for hole containment by picking an arbitrary point on each counterclockwise polygon:

https://github.com/mbostock/shapefile/blob/master/shp/polygon.js

Performing this test on every point on every counterclockwise polygon would make it much slower. And of course it still wouldn’t handle certain malformed inputs.

Your best bet here is to fix the GeoJSON (or shapefile) manually to correct the offending hole, so that there’s only a single ring. This library doesn’t do any complex geometry so it won’t be able to fix invalid inputs. Sorry!

**Comment by mbostock** [comment]
No plans to fix input geometry that does not conform to this library’s requirements, so closing this issue.
