### ISSUE TITLE
Error: error in unzip: code 9

### ISSUE THREAD

**Issue by humphd** [mbostock/shapefile#61]
I'm trying to convert a file with `shp2json`, and getting an error:

```
$ curl -o street-tree-data-wgs84.zip https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/6ac4569e-fd37-4cbc-ac63-db3624c5f6a2/resource/c1229af1-8ab6-4c71-b131-8be12da59c8e/download/street-tree-data-wgs84.zip
$ unzip street-tree-data-wgs84.zip
Archive:  street-tree-data-wgs84.zip
  inflating: TMMS_Open_Data_WGS84.shp.xml
  inflating: TMMS_Open_Data_WGS84.shx
 extracting: TMMS_Open_Data_WGS84.cpg
  inflating: TMMS_Open_Data_WGS84.dbf
  inflating: TMMS_Open_Data_WGS84.prj
  inflating: TMMS_Open_Data_WGS84.sbn
  inflating: TMMS_Open_Data_WGS84.sbx
  inflating: TMMS_Open_Data_WGS84.shp
$ shp2json TMMS_Open_Data_WGS84.shp -o trees.json
Error: error in unzip: code 9
```

The file in question is [here](https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/6ac4569e-fd37-4cbc-ac63-db3624c5f6a2/resource/c1229af1-8ab6-4c71-b131-8be12da59c8e/download/street-tree-data-wgs84.zip).

It's possible this is me doing something wrong, as I don't know much about SHP files (which is why I was trying to convert).  I've filed in case it's a real bug.

**Comment by mbloch** [comment]
You might want to take this problem to the `shp2json` issue tracker. It looks like this error has already been reported there: https://github.com/substack/shp2json/issues/23

**Comment by humphd** [comment]
Ah, thanks.  Sorry I filed here vs. there in the first place.  Thanks for the link.

**Comment by mbostock** [comment]
@mbloch This library also exports a `shp2json` binary. @humphd Are you using this library’s shp2json or substack’s shp2json?

**Comment by mbloch** [comment]
Gosh, sorry about that. @mbostock... 

I took a look at the file (because I'm always looking for tricky Shapefiles).

The file is unusual for a POINT type Shapefile, in that the features that lack valid coordinates use -1.7976931348623157e+308 for their x and y coordinate values. The Shapefile format uses large negative values to indicate null values in attribute data, but I haven't seen this convention used for coordinate data before.

The usual way to store Shapefile features without valid geometry is as a NULL type feature.

This might cause errors in some tools.

**Comment by humphd** [comment]
@mbostock I didn't realize there were two, so was using substack's.  I've retested the above failing case with `shapefile` instead and it worked perfectly!  Sorry for the confusion.

**Comment by mbostock** [comment]
Great!
