### ISSUE TITLE
Support for browser parsing?

### ISSUE THREAD

**Issue by iwillig** [mbostock/shapefile#7]
It seems like the current implementation is dependent on node.js. Do you have any thoughts on providing support for a pure client side parser? 

I thought about this a tiny bit and it seems like one could use the new TypedArrays in Javascript to do this. The DataView object allows for one to specify the endianness of the byte array, which is something we need for reading shapefiles. 

http://www.khronos.org/registry/typedarray/specs/latest/#8
Perhaps if the parsing of the features were moved into stream independent functions we could dynamically support both a stream client for node and one for the browser. 

Or maybe this is out of scope for this project so feel free to close if so. 
Thanks.

**Comment by nmccready** [comment]
@iwillig no need use this one https://github.com/calvinmetcalf/shapefile-js

**Comment by mbostock** [comment]
Somewhat released to #15, except that’s kinda more about Node streams. I’ve got a new “source” abstraction (see [file-source](https://github.com/mbostock/file-source)) that was the basis of a rewrite I just merged, and in theory it should be possible to substitute other source implementations to allow parsing of in-memory blobs or streaming fetches in the browser. But I’m not entirely sure what the distribution strategy will be for that since it’s pretty convenient to accept a string path for Node.

**Comment by mbostock** [comment]
Merging into #15.

**Comment by mbostock** [comment]
Now available in 0.5!
